//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.tows = new HashSet<tow>();
            this.vehicle_own = new HashSet<vehicle_own>();
        }
    
        public int v_id { get; set; }
        public string v_num_plate { get; set; }
        public string v_type { get; set; }
        public string v_color { get; set; }
        public string v_model { get; set; }
        public byte[] v_picture { get; set; }
        public string v_brand { get; set; }
        public string v_chassis { get; set; }
        public string v_generation { get; set; }
        public string v_engine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tow> tows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle_own> vehicle_own { get; set; }
    }
}
